keys:
  - &server age1...
  - &user1_server age1...

creation_rules:
  - path_regex: modules/hosts/server/server_secrets\.yaml$
    key_groups:
      - age:
          - *server
          - *user1_server
  - path_regex: modules/users/user1/user1_secrets\.yaml$
    key_groups:
      - age:
          - *user1_server
          - *server
